# Generated by Django 5.2 on 2025-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='meal_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('appetizers', 'Appetizers'), ('main_courses', 'Main Courses'), ('desserts', 'Desserts')], max_length=200),
        ),
    ]
